### ISSUE TITLE
Checkup since a new package is unknown in the mirror

### ISSUE THREAD

**Issue by Levivb** [composer/mirror#3] opened 2020-10-27 19:23 UTC
Hey,

I'm extensively using this code to run a private self hosted packagist mirror.

Today a new package has been added to packagist: https://packagist.org/packages/fakerphp/faker at 2020-10-27 13:44 UTC. 
Unfortunately, I'm unable to download the package through composer when I run `composer require fakerphp/faker`

The error:
```
$ composer update --no-scripts
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fakerphp/faker, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

As soon as I remove 
```
    {
      "packagist": false
    },
```
from the `composer.json`, making a fallback to the public repository I can see from the outgoing network, the package can be installed succesfully.

My mirror.config.php:

```php
<?php

return [
    // directory where metadata files will get saved
    'target_dir' => './public',

    // user agent describing your mirror node, if possible include domain name of mirror
    'user_agent' => 'Maximum Composer Mirror',

    // source repository URL
    'repo_url' => 'https://repo.packagist.org',

    // source repository hostname (optional, will guess from repo_url)
    //'repo_hostname' => 'repo.packagist.org',

    // source API URL
    'api_url' => 'https://packagist.org',

    // how many times the script will run the mirroring step before exiting
    'iterations' => 120,

    // how many seconds to wait between mirror runs
    'iteration_interval' => 30,

    // set this to false if you do not run the --v1 mirror job, to ensure that the v2 will then take care of syncing packages.json
    'has_v1_mirror' => false,
];
```

and in supervisor only `--v2` is configured and seems to be okay-ish as `ps aux | grep php` shows:
```
maximum   7480 58.4 14.1 1661384 1157900 ?     R    20:00   9:03 php /var/www/packagist-mirror-official/mirror.php --v2
```

Last Sunday I disabled `--v1`. 

`ls -al public/p | wc -l` shows `108853` directories and `ls -al public/p2 | wc -l` shows `99456` directories.
So there seems to be a discrepancy there although I don't know if `p` and `p2` should yield the same result.

Is there anything that I'm missing here or does this mirroring-repo need an update after the composer 2 release? Or does the currently running `--v2` mirror simply need more time since `--v1` is disabled since Sunday?

**Comment by Levivb** [comment] 2020-10-27 19:26
Ow btw, I did notice quite some errors in the log like this:

```
Symfony\Component\HttpClient\Exception\TransportException Idle timeout reached for "https://repo.packagist.org/p2/rehmatworks/laravel-reviewable~dev.json
```


So I did increate the Http::create timeouts:
```diff
        $this->client = HttpClient::create(
            [
                'headers' => [
                    'User-Agent' => $this->userAgent,
                    'Host' => $this->hostname,
                ],
-                'timeout' => 10,
+               'timeout' => 30,
-                'max_duration' => 15,
+                'max_duration' => 45,
                'http_version' => '2.0',
            ]
        );
```

That at least creates a longer running time but doesn't really fix the issue at hand

**Comment by Seldaek** [comment] 2020-10-27 20:15
I can't say that I have much experience running this without --v1, as all the official mirrors use --v1 + --v2 + --gc as per the README recommendation.

That said, new packages should get synced just fine as well without the --v1.. so I am not sure what's up. I'd 

The timeouts I see as well, and I'm not sure how to fix those, it seems more like random connection failures than timeouts due to slowness.

As a bruteforce fix you can delete `last_metadata_timestamp` then start the script again which will force a resync of the entire data (it should still avoid downloading the content that is already up to date though, using If-Modified-Since).

**Comment by Levivb** [comment] 2020-10-27 23:26
Thanks for your prompt response!

I re-enabled the `--v1` sync, removed `last_metadata_timestamp` and the `p2` directory (to be sure) and started a (re)sync.
Currently `p2` holds `95749` directories and seems to have completed(?)

`ls -al p/faker*` shows `faker/          fakerino/       fakerphp/       fakerpp/        faker-provider/`
while
`ls -al p2/faker*` shows `faker/          fakerino/       fakerpp/        faker-provider/`, missing the `fakerphp` which is available in `p`.
Note: downgrading composer to v1 does allow `composer update` to finish

I'de have to dig into the syncing a bit more to rule stuff out from the outside, I won't be at my computer tomorrow. So hopefully the day after. Not sure, but can you check if packagist does have vendor `fakerphp` with package `faker` in it's p2 list? Maybe it's a hidden bug from the composer v2 transition in which packagist doesn't pick up on new packages in the composer 2 listings?

Thanks for thinking along anyway :)

**Comment by boydseltenrijch** [comment] 2020-10-28 10:31
Hi @Seldaek and @Levivb,

I think it's due to a combination of how the syncing for v2 works, and a bug/sync delay in packagist.org.
The v2 does only a full sync the first time / when a resync is requested. Otherwise it will only update the changes.

But packagist.org doesn't always returns all packages...
This probably has to due with the way it's setup.

When I run the following commands, we can see that only on some ip addresses faker is returned in the `/packages/list.json`

```
for i in {1..100}; do dig a packagist.org @ns-601.awsdns-11.net +short >> packagist_ips.txt; done
sort -u packagist_ips.txt > uniq_packagist_ips.txt
while read ip; do curl -s --resolve "packagist.org:443:$ip" https://packagist.org/packages/list.json | jq '.[]' | grep -q fakerphp && echo "fakerphp/faker found on $ip" || echo "fakerphp/faker not found on $ip"; done < uniq_packagist_ips.txt


fakerphp/faker not found on 217.182.91.150
fakerphp/faker not found on 217.182.92.110
fakerphp/faker not found on 51.38.227.34
fakerphp/faker found on 51.77.109.217
fakerphp/faker found on 54.37.131.18
fakerphp/faker found on 54.37.2.184
fakerphp/faker found on 54.37.4.73
fakerphp/faker not found on 54.38.136.239
```

We can also see the the filecount is different per ip address
```
while read ip; do curl -s --resolve "packagist.org:443:$ip" https://packagist.org/packages/list.json | jq '.[]' | wc -l | awk '{print "'$ip' filecount:" $1}'; done < uniq_packagist_ips.txt


217.182.91.150 filecount:275821
217.182.92.110 filecount:275821
51.38.227.34 filecount:275821
51.77.109.217 filecount:275821
54.37.131.18 filecount:275821
54.37.2.184 filecount:281460
54.37.4.73 filecount:281460
54.38.136.239 filecount:281460
```

@Levivb, so for now it's probably best to add the following to `/etc/hosts` and do a new resync.

```
54.38.136.239 packagist.org
```

**Comment by Seldaek** [comment] 2020-10-28 14:00
@boydseltenrijch ah thanks that's a good find. That's a caching issue, and explains why the resync wouldn't fix it. https://github.com/composer/mirror/commit/06b66a6067dffed1a3374618fcf98911f0342350 fixes that issue by busting through our reverse cache. 

Please don't hardcode IPs in the hosts file to avoid long term issues :)

As for the other issue, of why the package got missing in the first place.. I think I found the cause, will work on a patch in a bit.

**Comment by Seldaek** [comment] 2020-10-28 16:14
OK I believe this fixes it, but I think only time will tell if this happens again or not with newly submitted packages

**Comment by Seldaek** [comment] 2020-10-28 18:15
Did a full resync on all mirrors, total count for `find /path/to/p2/ -type f -name *.json | wc -l` should be around 563'000 FYI.

**Comment by Levivb** [comment] 2020-10-29 08:57
Thanks for look further into it @Seldaek and @boydseltenrijch that's a very nice find indeed!

The `uniqid` cache buster does indeed seem to fix it for us for now as the p2 directory does contain 563.000+ files and fakerphp is among one of them. I do understand that this might be a temporary solution since breaking through the caching layers like this is somewhat undesirable from your side.

Thanks for now and let me know if you need any further information whatsoever :)

**Comment by Seldaek** [comment] 2020-10-29 09:01
The API needs to be cached for other uses in Composer which need fast responses, but in this instance it's fine to keep the cache busting as mirror resyncs aren't frequent, and they can wait a couple seconds for a response.

AFAIK it's all fixed now but if you do find more issues please do tell.

**Closed as completed by Seldaek** 2020-10-29 09:01 UTC

**Comment by Seldaek** [comment] 2020-11-25 12:11
@Levivb are you running a full resync once an hour or so from 217.119.4.172?

**Comment by Levivb** [comment] 2020-11-25 12:13
Hey @Seldaek that is the ip from the server running our mirror. But I'm not aware a full resync is running.
I'll check it out real quick. But if all works according to intention only the v1 and v2 mirror processes are running via supervisor

**Comment by Seldaek** [comment] 2020-11-25 12:25
I see lots of resyncs requests on our end. Are you sure the `last_metadata_timestamp` file can be written next to the mirror.php?

**Comment by Levivb** [comment] 2020-11-25 12:40
hm, good one. 

cron (for garbage collector) and sync processes via supervisor are the only processes running but checking the logs and the `last_metadata_timestamp` file your suspicion seems correct:

```
Fatal error: Uncaught ErrorException: file_put_contents(./last_metadata_timestamp): failed to open stream: Permission denied in /var/www/packagist-mirror-official/mirror.php:198
```

```
$ ll packagist-mirror-official/last_metadata_timestamp
-rw-rw-r-- 1 maximum maximum 14 Oct 28 14:13 packagist-mirror-official/last_metadata_timestamp
```

so `28th October` was the last update of `last_metadata_timestamp`. I changed the permissions of the file, pulled changes from remote and restarted supervisor. Let's see how that goes

Thanks for noticing! :)
Hope it didn't cause to much problems on your end 😬

**Comment by Seldaek** [comment] 2020-11-25 12:46
Nope no big deal, I just noticed and thought I'd let you know. You may want to put a better user-agent though so I can reach out more easily. I luckily found this issue because you posted the user agent in the config above so google found it.. 

I'll fix the mirror script so it does not start if last_metadata_timestamp can not be written I guess ;)

**Comment by Levivb** [comment] 2020-11-25 17:24
Hehe, yea good thinking! I pulled the new changes and restarted supervisor.

I did notice changing the permissions of `last_metadata_timestamp` didn't fix it earlier, so I checked some further.

Upon inspection of the source code I noticed the `last_metadata_timestamp` is written to the directory the script is executed from. So if you do `cd /opt/some/random/dir` and run `php /var/www/packagist-mirror/mirror.php`, the `last_metadata_timestamp` file will be written in `/opt/some/random/dir/`.
Since I'm not entirely sure where supervisor's cwd is, I updated the configuration from supervisor to take the cwd into account. 

So
```
command=php /var/www/packagist-mirror-official/mirror.php --v1
```

becomes:
```
command=php mirror.php --v1
directory=/var/www/packagist-mirror-official
```

modification date of `last_metadata_timestamp` is `14 Nov 25 18:21`, so I assume it's fixed :)

I'll change the user agent later this week to something sensible. It's indeed a good idea to put some way of contact info in there.

**Comment by Seldaek** [comment] 2020-11-25 18:52
Ah true, it expects working directory to be the script's path. I'll fix that to make it an absolute path, thanks for the feedback.

**Comment by Seldaek** [comment] 2020-11-26 08:53
https://github.com/composer/mirror/commit/5099f58eed2fcf74299169f5acc450160e5b8db4

**Comment by Seldaek** [comment] 2025-03-04 11:53
@Levivb are you still the one running "Maximum Composer Mirror" from IP 217.119.4.61 ? If so I'd need to see why you're doing so many requests.. It's either a misconfigured/outdated version of this repo, or it is some other custom code you're using? But anyway it is doing way too many requests and if I do not get an answer I'll have to ban it.

**Comment by Levivb** [comment] 2025-03-04 12:28
Hey @Seldaek I'll forward this to my former employer. There shouldn't be any custom code in the repo, so perhaps running a `git pull` and `composer install` helps. I've forwarded it so I hope they can check it out!

**Comment by Levivb** [comment] 2025-03-06 13:50
I've received a message that the issue should be resolved :)

I didn't receive any details, so what it might have caused it is unknown to me

**Comment by Seldaek** [comment] 2025-03-06 14:25
Looks good on my end too, thanks!
